/*
Private Space API

Description of the Private Space API

API version: 1.0.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package private_space

import (
	"encoding/json"
)

// checks if the PrivateSpaceNetworkEditableInternalDns type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &PrivateSpaceNetworkEditableInternalDns{}

// PrivateSpaceNetworkEditableInternalDns The internal DNS config of the VPC that the Private Space uses.
type PrivateSpaceNetworkEditableInternalDns struct {
	DnsServers []string `json:"dnsServers,omitempty"`
	SpecialDomains []string `json:"specialDomains,omitempty"`
}

// NewPrivateSpaceNetworkEditableInternalDns instantiates a new PrivateSpaceNetworkEditableInternalDns object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPrivateSpaceNetworkEditableInternalDns() *PrivateSpaceNetworkEditableInternalDns {
	this := PrivateSpaceNetworkEditableInternalDns{}
	return &this
}

// NewPrivateSpaceNetworkEditableInternalDnsWithDefaults instantiates a new PrivateSpaceNetworkEditableInternalDns object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPrivateSpaceNetworkEditableInternalDnsWithDefaults() *PrivateSpaceNetworkEditableInternalDns {
	this := PrivateSpaceNetworkEditableInternalDns{}
	return &this
}

// GetDnsServers returns the DnsServers field value if set, zero value otherwise.
func (o *PrivateSpaceNetworkEditableInternalDns) GetDnsServers() []string {
	if o == nil || IsNil(o.DnsServers) {
		var ret []string
		return ret
	}
	return o.DnsServers
}

// GetDnsServersOk returns a tuple with the DnsServers field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PrivateSpaceNetworkEditableInternalDns) GetDnsServersOk() ([]string, bool) {
	if o == nil || IsNil(o.DnsServers) {
		return nil, false
	}
	return o.DnsServers, true
}

// HasDnsServers returns a boolean if a field has been set.
func (o *PrivateSpaceNetworkEditableInternalDns) HasDnsServers() bool {
	if o != nil && !IsNil(o.DnsServers) {
		return true
	}

	return false
}

// SetDnsServers gets a reference to the given []string and assigns it to the DnsServers field.
func (o *PrivateSpaceNetworkEditableInternalDns) SetDnsServers(v []string) {
	o.DnsServers = v
}

// GetSpecialDomains returns the SpecialDomains field value if set, zero value otherwise.
func (o *PrivateSpaceNetworkEditableInternalDns) GetSpecialDomains() []string {
	if o == nil || IsNil(o.SpecialDomains) {
		var ret []string
		return ret
	}
	return o.SpecialDomains
}

// GetSpecialDomainsOk returns a tuple with the SpecialDomains field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PrivateSpaceNetworkEditableInternalDns) GetSpecialDomainsOk() ([]string, bool) {
	if o == nil || IsNil(o.SpecialDomains) {
		return nil, false
	}
	return o.SpecialDomains, true
}

// HasSpecialDomains returns a boolean if a field has been set.
func (o *PrivateSpaceNetworkEditableInternalDns) HasSpecialDomains() bool {
	if o != nil && !IsNil(o.SpecialDomains) {
		return true
	}

	return false
}

// SetSpecialDomains gets a reference to the given []string and assigns it to the SpecialDomains field.
func (o *PrivateSpaceNetworkEditableInternalDns) SetSpecialDomains(v []string) {
	o.SpecialDomains = v
}

func (o PrivateSpaceNetworkEditableInternalDns) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o PrivateSpaceNetworkEditableInternalDns) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.DnsServers) {
		toSerialize["dnsServers"] = o.DnsServers
	}
	if !IsNil(o.SpecialDomains) {
		toSerialize["specialDomains"] = o.SpecialDomains
	}
	return toSerialize, nil
}

type NullablePrivateSpaceNetworkEditableInternalDns struct {
	value *PrivateSpaceNetworkEditableInternalDns
	isSet bool
}

func (v NullablePrivateSpaceNetworkEditableInternalDns) Get() *PrivateSpaceNetworkEditableInternalDns {
	return v.value
}

func (v *NullablePrivateSpaceNetworkEditableInternalDns) Set(val *PrivateSpaceNetworkEditableInternalDns) {
	v.value = val
	v.isSet = true
}

func (v NullablePrivateSpaceNetworkEditableInternalDns) IsSet() bool {
	return v.isSet
}

func (v *NullablePrivateSpaceNetworkEditableInternalDns) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePrivateSpaceNetworkEditableInternalDns(val *PrivateSpaceNetworkEditableInternalDns) *NullablePrivateSpaceNetworkEditableInternalDns {
	return &NullablePrivateSpaceNetworkEditableInternalDns{value: val, isSet: true}
}

func (v NullablePrivateSpaceNetworkEditableInternalDns) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePrivateSpaceNetworkEditableInternalDns) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


