/*
Exchange Apps

Description of the Exchange Apps API

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package exchange_apps

import (
	"encoding/json"
)

// checks if the GetExchangeAppContractsResponseInnerRequestedTierLimitsInner type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GetExchangeAppContractsResponseInnerRequestedTierLimitsInner{}

// GetExchangeAppContractsResponseInnerRequestedTierLimitsInner struct for GetExchangeAppContractsResponseInnerRequestedTierLimitsInner
type GetExchangeAppContractsResponseInnerRequestedTierLimitsInner struct {
	MaximumRequests *int32 `json:"maximumRequests,omitempty"`
	TimePeriodInMilliseconds *int32 `json:"timePeriodInMilliseconds,omitempty"`
}

// NewGetExchangeAppContractsResponseInnerRequestedTierLimitsInner instantiates a new GetExchangeAppContractsResponseInnerRequestedTierLimitsInner object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetExchangeAppContractsResponseInnerRequestedTierLimitsInner() *GetExchangeAppContractsResponseInnerRequestedTierLimitsInner {
	this := GetExchangeAppContractsResponseInnerRequestedTierLimitsInner{}
	return &this
}

// NewGetExchangeAppContractsResponseInnerRequestedTierLimitsInnerWithDefaults instantiates a new GetExchangeAppContractsResponseInnerRequestedTierLimitsInner object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetExchangeAppContractsResponseInnerRequestedTierLimitsInnerWithDefaults() *GetExchangeAppContractsResponseInnerRequestedTierLimitsInner {
	this := GetExchangeAppContractsResponseInnerRequestedTierLimitsInner{}
	return &this
}

// GetMaximumRequests returns the MaximumRequests field value if set, zero value otherwise.
func (o *GetExchangeAppContractsResponseInnerRequestedTierLimitsInner) GetMaximumRequests() int32 {
	if o == nil || IsNil(o.MaximumRequests) {
		var ret int32
		return ret
	}
	return *o.MaximumRequests
}

// GetMaximumRequestsOk returns a tuple with the MaximumRequests field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetExchangeAppContractsResponseInnerRequestedTierLimitsInner) GetMaximumRequestsOk() (*int32, bool) {
	if o == nil || IsNil(o.MaximumRequests) {
		return nil, false
	}
	return o.MaximumRequests, true
}

// HasMaximumRequests returns a boolean if a field has been set.
func (o *GetExchangeAppContractsResponseInnerRequestedTierLimitsInner) HasMaximumRequests() bool {
	if o != nil && !IsNil(o.MaximumRequests) {
		return true
	}

	return false
}

// SetMaximumRequests gets a reference to the given int32 and assigns it to the MaximumRequests field.
func (o *GetExchangeAppContractsResponseInnerRequestedTierLimitsInner) SetMaximumRequests(v int32) {
	o.MaximumRequests = &v
}

// GetTimePeriodInMilliseconds returns the TimePeriodInMilliseconds field value if set, zero value otherwise.
func (o *GetExchangeAppContractsResponseInnerRequestedTierLimitsInner) GetTimePeriodInMilliseconds() int32 {
	if o == nil || IsNil(o.TimePeriodInMilliseconds) {
		var ret int32
		return ret
	}
	return *o.TimePeriodInMilliseconds
}

// GetTimePeriodInMillisecondsOk returns a tuple with the TimePeriodInMilliseconds field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetExchangeAppContractsResponseInnerRequestedTierLimitsInner) GetTimePeriodInMillisecondsOk() (*int32, bool) {
	if o == nil || IsNil(o.TimePeriodInMilliseconds) {
		return nil, false
	}
	return o.TimePeriodInMilliseconds, true
}

// HasTimePeriodInMilliseconds returns a boolean if a field has been set.
func (o *GetExchangeAppContractsResponseInnerRequestedTierLimitsInner) HasTimePeriodInMilliseconds() bool {
	if o != nil && !IsNil(o.TimePeriodInMilliseconds) {
		return true
	}

	return false
}

// SetTimePeriodInMilliseconds gets a reference to the given int32 and assigns it to the TimePeriodInMilliseconds field.
func (o *GetExchangeAppContractsResponseInnerRequestedTierLimitsInner) SetTimePeriodInMilliseconds(v int32) {
	o.TimePeriodInMilliseconds = &v
}

func (o GetExchangeAppContractsResponseInnerRequestedTierLimitsInner) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GetExchangeAppContractsResponseInnerRequestedTierLimitsInner) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.MaximumRequests) {
		toSerialize["maximumRequests"] = o.MaximumRequests
	}
	if !IsNil(o.TimePeriodInMilliseconds) {
		toSerialize["timePeriodInMilliseconds"] = o.TimePeriodInMilliseconds
	}
	return toSerialize, nil
}

type NullableGetExchangeAppContractsResponseInnerRequestedTierLimitsInner struct {
	value *GetExchangeAppContractsResponseInnerRequestedTierLimitsInner
	isSet bool
}

func (v NullableGetExchangeAppContractsResponseInnerRequestedTierLimitsInner) Get() *GetExchangeAppContractsResponseInnerRequestedTierLimitsInner {
	return v.value
}

func (v *NullableGetExchangeAppContractsResponseInnerRequestedTierLimitsInner) Set(val *GetExchangeAppContractsResponseInnerRequestedTierLimitsInner) {
	v.value = val
	v.isSet = true
}

func (v NullableGetExchangeAppContractsResponseInnerRequestedTierLimitsInner) IsSet() bool {
	return v.isSet
}

func (v *NullableGetExchangeAppContractsResponseInnerRequestedTierLimitsInner) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetExchangeAppContractsResponseInnerRequestedTierLimitsInner(val *GetExchangeAppContractsResponseInnerRequestedTierLimitsInner) *NullableGetExchangeAppContractsResponseInnerRequestedTierLimitsInner {
	return &NullableGetExchangeAppContractsResponseInnerRequestedTierLimitsInner{value: val, isSet: true}
}

func (v NullableGetExchangeAppContractsResponseInnerRequestedTierLimitsInner) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetExchangeAppContractsResponseInnerRequestedTierLimitsInner) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


