/*
Exchange Apps

Description of the Exchange Apps API

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package exchange_apps

import (
	"encoding/json"
)

// checks if the PostExchangeAppsReponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &PostExchangeAppsReponse{}

// PostExchangeAppsReponse struct for PostExchangeAppsReponse
type PostExchangeAppsReponse struct {
	Id *int32 `json:"id,omitempty"`
	Name *string `json:"name,omitempty"`
	Description *string `json:"description,omitempty"`
	MasterOrganizationId *string `json:"masterOrganizationId,omitempty"`
	ClientId *string `json:"clientId,omitempty"`
	ClientSecret *string `json:"clientSecret,omitempty"`
	GrantTypes []string `json:"grantTypes,omitempty"`
	RedirectUri []string `json:"redirectUri,omitempty"`
	ClientProvider *PostExchangeAppsReponseClientProvider `json:"clientProvider,omitempty"`
}

// NewPostExchangeAppsReponse instantiates a new PostExchangeAppsReponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPostExchangeAppsReponse() *PostExchangeAppsReponse {
	this := PostExchangeAppsReponse{}
	return &this
}

// NewPostExchangeAppsReponseWithDefaults instantiates a new PostExchangeAppsReponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPostExchangeAppsReponseWithDefaults() *PostExchangeAppsReponse {
	this := PostExchangeAppsReponse{}
	return &this
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *PostExchangeAppsReponse) GetId() int32 {
	if o == nil || IsNil(o.Id) {
		var ret int32
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PostExchangeAppsReponse) GetIdOk() (*int32, bool) {
	if o == nil || IsNil(o.Id) {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *PostExchangeAppsReponse) HasId() bool {
	if o != nil && !IsNil(o.Id) {
		return true
	}

	return false
}

// SetId gets a reference to the given int32 and assigns it to the Id field.
func (o *PostExchangeAppsReponse) SetId(v int32) {
	o.Id = &v
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *PostExchangeAppsReponse) GetName() string {
	if o == nil || IsNil(o.Name) {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PostExchangeAppsReponse) GetNameOk() (*string, bool) {
	if o == nil || IsNil(o.Name) {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *PostExchangeAppsReponse) HasName() bool {
	if o != nil && !IsNil(o.Name) {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *PostExchangeAppsReponse) SetName(v string) {
	o.Name = &v
}

// GetDescription returns the Description field value if set, zero value otherwise.
func (o *PostExchangeAppsReponse) GetDescription() string {
	if o == nil || IsNil(o.Description) {
		var ret string
		return ret
	}
	return *o.Description
}

// GetDescriptionOk returns a tuple with the Description field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PostExchangeAppsReponse) GetDescriptionOk() (*string, bool) {
	if o == nil || IsNil(o.Description) {
		return nil, false
	}
	return o.Description, true
}

// HasDescription returns a boolean if a field has been set.
func (o *PostExchangeAppsReponse) HasDescription() bool {
	if o != nil && !IsNil(o.Description) {
		return true
	}

	return false
}

// SetDescription gets a reference to the given string and assigns it to the Description field.
func (o *PostExchangeAppsReponse) SetDescription(v string) {
	o.Description = &v
}

// GetMasterOrganizationId returns the MasterOrganizationId field value if set, zero value otherwise.
func (o *PostExchangeAppsReponse) GetMasterOrganizationId() string {
	if o == nil || IsNil(o.MasterOrganizationId) {
		var ret string
		return ret
	}
	return *o.MasterOrganizationId
}

// GetMasterOrganizationIdOk returns a tuple with the MasterOrganizationId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PostExchangeAppsReponse) GetMasterOrganizationIdOk() (*string, bool) {
	if o == nil || IsNil(o.MasterOrganizationId) {
		return nil, false
	}
	return o.MasterOrganizationId, true
}

// HasMasterOrganizationId returns a boolean if a field has been set.
func (o *PostExchangeAppsReponse) HasMasterOrganizationId() bool {
	if o != nil && !IsNil(o.MasterOrganizationId) {
		return true
	}

	return false
}

// SetMasterOrganizationId gets a reference to the given string and assigns it to the MasterOrganizationId field.
func (o *PostExchangeAppsReponse) SetMasterOrganizationId(v string) {
	o.MasterOrganizationId = &v
}

// GetClientId returns the ClientId field value if set, zero value otherwise.
func (o *PostExchangeAppsReponse) GetClientId() string {
	if o == nil || IsNil(o.ClientId) {
		var ret string
		return ret
	}
	return *o.ClientId
}

// GetClientIdOk returns a tuple with the ClientId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PostExchangeAppsReponse) GetClientIdOk() (*string, bool) {
	if o == nil || IsNil(o.ClientId) {
		return nil, false
	}
	return o.ClientId, true
}

// HasClientId returns a boolean if a field has been set.
func (o *PostExchangeAppsReponse) HasClientId() bool {
	if o != nil && !IsNil(o.ClientId) {
		return true
	}

	return false
}

// SetClientId gets a reference to the given string and assigns it to the ClientId field.
func (o *PostExchangeAppsReponse) SetClientId(v string) {
	o.ClientId = &v
}

// GetClientSecret returns the ClientSecret field value if set, zero value otherwise.
func (o *PostExchangeAppsReponse) GetClientSecret() string {
	if o == nil || IsNil(o.ClientSecret) {
		var ret string
		return ret
	}
	return *o.ClientSecret
}

// GetClientSecretOk returns a tuple with the ClientSecret field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PostExchangeAppsReponse) GetClientSecretOk() (*string, bool) {
	if o == nil || IsNil(o.ClientSecret) {
		return nil, false
	}
	return o.ClientSecret, true
}

// HasClientSecret returns a boolean if a field has been set.
func (o *PostExchangeAppsReponse) HasClientSecret() bool {
	if o != nil && !IsNil(o.ClientSecret) {
		return true
	}

	return false
}

// SetClientSecret gets a reference to the given string and assigns it to the ClientSecret field.
func (o *PostExchangeAppsReponse) SetClientSecret(v string) {
	o.ClientSecret = &v
}

// GetGrantTypes returns the GrantTypes field value if set, zero value otherwise.
func (o *PostExchangeAppsReponse) GetGrantTypes() []string {
	if o == nil || IsNil(o.GrantTypes) {
		var ret []string
		return ret
	}
	return o.GrantTypes
}

// GetGrantTypesOk returns a tuple with the GrantTypes field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PostExchangeAppsReponse) GetGrantTypesOk() ([]string, bool) {
	if o == nil || IsNil(o.GrantTypes) {
		return nil, false
	}
	return o.GrantTypes, true
}

// HasGrantTypes returns a boolean if a field has been set.
func (o *PostExchangeAppsReponse) HasGrantTypes() bool {
	if o != nil && !IsNil(o.GrantTypes) {
		return true
	}

	return false
}

// SetGrantTypes gets a reference to the given []string and assigns it to the GrantTypes field.
func (o *PostExchangeAppsReponse) SetGrantTypes(v []string) {
	o.GrantTypes = v
}

// GetRedirectUri returns the RedirectUri field value if set, zero value otherwise.
func (o *PostExchangeAppsReponse) GetRedirectUri() []string {
	if o == nil || IsNil(o.RedirectUri) {
		var ret []string
		return ret
	}
	return o.RedirectUri
}

// GetRedirectUriOk returns a tuple with the RedirectUri field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PostExchangeAppsReponse) GetRedirectUriOk() ([]string, bool) {
	if o == nil || IsNil(o.RedirectUri) {
		return nil, false
	}
	return o.RedirectUri, true
}

// HasRedirectUri returns a boolean if a field has been set.
func (o *PostExchangeAppsReponse) HasRedirectUri() bool {
	if o != nil && !IsNil(o.RedirectUri) {
		return true
	}

	return false
}

// SetRedirectUri gets a reference to the given []string and assigns it to the RedirectUri field.
func (o *PostExchangeAppsReponse) SetRedirectUri(v []string) {
	o.RedirectUri = v
}

// GetClientProvider returns the ClientProvider field value if set, zero value otherwise.
func (o *PostExchangeAppsReponse) GetClientProvider() PostExchangeAppsReponseClientProvider {
	if o == nil || IsNil(o.ClientProvider) {
		var ret PostExchangeAppsReponseClientProvider
		return ret
	}
	return *o.ClientProvider
}

// GetClientProviderOk returns a tuple with the ClientProvider field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PostExchangeAppsReponse) GetClientProviderOk() (*PostExchangeAppsReponseClientProvider, bool) {
	if o == nil || IsNil(o.ClientProvider) {
		return nil, false
	}
	return o.ClientProvider, true
}

// HasClientProvider returns a boolean if a field has been set.
func (o *PostExchangeAppsReponse) HasClientProvider() bool {
	if o != nil && !IsNil(o.ClientProvider) {
		return true
	}

	return false
}

// SetClientProvider gets a reference to the given PostExchangeAppsReponseClientProvider and assigns it to the ClientProvider field.
func (o *PostExchangeAppsReponse) SetClientProvider(v PostExchangeAppsReponseClientProvider) {
	o.ClientProvider = &v
}

func (o PostExchangeAppsReponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o PostExchangeAppsReponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Id) {
		toSerialize["id"] = o.Id
	}
	if !IsNil(o.Name) {
		toSerialize["name"] = o.Name
	}
	if !IsNil(o.Description) {
		toSerialize["description"] = o.Description
	}
	if !IsNil(o.MasterOrganizationId) {
		toSerialize["masterOrganizationId"] = o.MasterOrganizationId
	}
	if !IsNil(o.ClientId) {
		toSerialize["clientId"] = o.ClientId
	}
	if !IsNil(o.ClientSecret) {
		toSerialize["clientSecret"] = o.ClientSecret
	}
	if !IsNil(o.GrantTypes) {
		toSerialize["grantTypes"] = o.GrantTypes
	}
	if !IsNil(o.RedirectUri) {
		toSerialize["redirectUri"] = o.RedirectUri
	}
	if !IsNil(o.ClientProvider) {
		toSerialize["clientProvider"] = o.ClientProvider
	}
	return toSerialize, nil
}

type NullablePostExchangeAppsReponse struct {
	value *PostExchangeAppsReponse
	isSet bool
}

func (v NullablePostExchangeAppsReponse) Get() *PostExchangeAppsReponse {
	return v.value
}

func (v *NullablePostExchangeAppsReponse) Set(val *PostExchangeAppsReponse) {
	v.value = val
	v.isSet = true
}

func (v NullablePostExchangeAppsReponse) IsSet() bool {
	return v.isSet
}

func (v *NullablePostExchangeAppsReponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePostExchangeAppsReponse(val *PostExchangeAppsReponse) *NullablePostExchangeAppsReponse {
	return &NullablePostExchangeAppsReponse{value: val, isSet: true}
}

func (v NullablePostExchangeAppsReponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePostExchangeAppsReponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


