/*
Exchange Apps

Description of the Exchange Apps API

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package exchange_apps

import (
	"encoding/json"
)

// checks if the GetExchangeAppsResponseInner type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GetExchangeAppsResponseInner{}

// GetExchangeAppsResponseInner struct for GetExchangeAppsResponseInner
type GetExchangeAppsResponseInner struct {
	Name *string `json:"name,omitempty"`
	Description *string `json:"description,omitempty"`
	Url NullableString `json:"url,omitempty"`
	MasterOrganizationId *string `json:"masterOrganizationId,omitempty"`
	Id *int32 `json:"id,omitempty"`
	ClientId *string `json:"clientId,omitempty"`
	ClientSecret *string `json:"clientSecret,omitempty"`
	ClientProvider *PostExchangeAppsReponseClientProvider `json:"clientProvider,omitempty"`
	GrantTypes []string `json:"grantTypes,omitempty"`
	RedirectUri []string `json:"redirectUri,omitempty"`
}

// NewGetExchangeAppsResponseInner instantiates a new GetExchangeAppsResponseInner object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetExchangeAppsResponseInner() *GetExchangeAppsResponseInner {
	this := GetExchangeAppsResponseInner{}
	return &this
}

// NewGetExchangeAppsResponseInnerWithDefaults instantiates a new GetExchangeAppsResponseInner object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetExchangeAppsResponseInnerWithDefaults() *GetExchangeAppsResponseInner {
	this := GetExchangeAppsResponseInner{}
	return &this
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *GetExchangeAppsResponseInner) GetName() string {
	if o == nil || IsNil(o.Name) {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetExchangeAppsResponseInner) GetNameOk() (*string, bool) {
	if o == nil || IsNil(o.Name) {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *GetExchangeAppsResponseInner) HasName() bool {
	if o != nil && !IsNil(o.Name) {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *GetExchangeAppsResponseInner) SetName(v string) {
	o.Name = &v
}

// GetDescription returns the Description field value if set, zero value otherwise.
func (o *GetExchangeAppsResponseInner) GetDescription() string {
	if o == nil || IsNil(o.Description) {
		var ret string
		return ret
	}
	return *o.Description
}

// GetDescriptionOk returns a tuple with the Description field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetExchangeAppsResponseInner) GetDescriptionOk() (*string, bool) {
	if o == nil || IsNil(o.Description) {
		return nil, false
	}
	return o.Description, true
}

// HasDescription returns a boolean if a field has been set.
func (o *GetExchangeAppsResponseInner) HasDescription() bool {
	if o != nil && !IsNil(o.Description) {
		return true
	}

	return false
}

// SetDescription gets a reference to the given string and assigns it to the Description field.
func (o *GetExchangeAppsResponseInner) SetDescription(v string) {
	o.Description = &v
}

// GetUrl returns the Url field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *GetExchangeAppsResponseInner) GetUrl() string {
	if o == nil || IsNil(o.Url.Get()) {
		var ret string
		return ret
	}
	return *o.Url.Get()
}

// GetUrlOk returns a tuple with the Url field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *GetExchangeAppsResponseInner) GetUrlOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Url.Get(), o.Url.IsSet()
}

// HasUrl returns a boolean if a field has been set.
func (o *GetExchangeAppsResponseInner) HasUrl() bool {
	if o != nil && o.Url.IsSet() {
		return true
	}

	return false
}

// SetUrl gets a reference to the given NullableString and assigns it to the Url field.
func (o *GetExchangeAppsResponseInner) SetUrl(v string) {
	o.Url.Set(&v)
}
// SetUrlNil sets the value for Url to be an explicit nil
func (o *GetExchangeAppsResponseInner) SetUrlNil() {
	o.Url.Set(nil)
}

// UnsetUrl ensures that no value is present for Url, not even an explicit nil
func (o *GetExchangeAppsResponseInner) UnsetUrl() {
	o.Url.Unset()
}

// GetMasterOrganizationId returns the MasterOrganizationId field value if set, zero value otherwise.
func (o *GetExchangeAppsResponseInner) GetMasterOrganizationId() string {
	if o == nil || IsNil(o.MasterOrganizationId) {
		var ret string
		return ret
	}
	return *o.MasterOrganizationId
}

// GetMasterOrganizationIdOk returns a tuple with the MasterOrganizationId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetExchangeAppsResponseInner) GetMasterOrganizationIdOk() (*string, bool) {
	if o == nil || IsNil(o.MasterOrganizationId) {
		return nil, false
	}
	return o.MasterOrganizationId, true
}

// HasMasterOrganizationId returns a boolean if a field has been set.
func (o *GetExchangeAppsResponseInner) HasMasterOrganizationId() bool {
	if o != nil && !IsNil(o.MasterOrganizationId) {
		return true
	}

	return false
}

// SetMasterOrganizationId gets a reference to the given string and assigns it to the MasterOrganizationId field.
func (o *GetExchangeAppsResponseInner) SetMasterOrganizationId(v string) {
	o.MasterOrganizationId = &v
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *GetExchangeAppsResponseInner) GetId() int32 {
	if o == nil || IsNil(o.Id) {
		var ret int32
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetExchangeAppsResponseInner) GetIdOk() (*int32, bool) {
	if o == nil || IsNil(o.Id) {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *GetExchangeAppsResponseInner) HasId() bool {
	if o != nil && !IsNil(o.Id) {
		return true
	}

	return false
}

// SetId gets a reference to the given int32 and assigns it to the Id field.
func (o *GetExchangeAppsResponseInner) SetId(v int32) {
	o.Id = &v
}

// GetClientId returns the ClientId field value if set, zero value otherwise.
func (o *GetExchangeAppsResponseInner) GetClientId() string {
	if o == nil || IsNil(o.ClientId) {
		var ret string
		return ret
	}
	return *o.ClientId
}

// GetClientIdOk returns a tuple with the ClientId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetExchangeAppsResponseInner) GetClientIdOk() (*string, bool) {
	if o == nil || IsNil(o.ClientId) {
		return nil, false
	}
	return o.ClientId, true
}

// HasClientId returns a boolean if a field has been set.
func (o *GetExchangeAppsResponseInner) HasClientId() bool {
	if o != nil && !IsNil(o.ClientId) {
		return true
	}

	return false
}

// SetClientId gets a reference to the given string and assigns it to the ClientId field.
func (o *GetExchangeAppsResponseInner) SetClientId(v string) {
	o.ClientId = &v
}

// GetClientSecret returns the ClientSecret field value if set, zero value otherwise.
func (o *GetExchangeAppsResponseInner) GetClientSecret() string {
	if o == nil || IsNil(o.ClientSecret) {
		var ret string
		return ret
	}
	return *o.ClientSecret
}

// GetClientSecretOk returns a tuple with the ClientSecret field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetExchangeAppsResponseInner) GetClientSecretOk() (*string, bool) {
	if o == nil || IsNil(o.ClientSecret) {
		return nil, false
	}
	return o.ClientSecret, true
}

// HasClientSecret returns a boolean if a field has been set.
func (o *GetExchangeAppsResponseInner) HasClientSecret() bool {
	if o != nil && !IsNil(o.ClientSecret) {
		return true
	}

	return false
}

// SetClientSecret gets a reference to the given string and assigns it to the ClientSecret field.
func (o *GetExchangeAppsResponseInner) SetClientSecret(v string) {
	o.ClientSecret = &v
}

// GetClientProvider returns the ClientProvider field value if set, zero value otherwise.
func (o *GetExchangeAppsResponseInner) GetClientProvider() PostExchangeAppsReponseClientProvider {
	if o == nil || IsNil(o.ClientProvider) {
		var ret PostExchangeAppsReponseClientProvider
		return ret
	}
	return *o.ClientProvider
}

// GetClientProviderOk returns a tuple with the ClientProvider field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetExchangeAppsResponseInner) GetClientProviderOk() (*PostExchangeAppsReponseClientProvider, bool) {
	if o == nil || IsNil(o.ClientProvider) {
		return nil, false
	}
	return o.ClientProvider, true
}

// HasClientProvider returns a boolean if a field has been set.
func (o *GetExchangeAppsResponseInner) HasClientProvider() bool {
	if o != nil && !IsNil(o.ClientProvider) {
		return true
	}

	return false
}

// SetClientProvider gets a reference to the given PostExchangeAppsReponseClientProvider and assigns it to the ClientProvider field.
func (o *GetExchangeAppsResponseInner) SetClientProvider(v PostExchangeAppsReponseClientProvider) {
	o.ClientProvider = &v
}

// GetGrantTypes returns the GrantTypes field value if set, zero value otherwise.
func (o *GetExchangeAppsResponseInner) GetGrantTypes() []string {
	if o == nil || IsNil(o.GrantTypes) {
		var ret []string
		return ret
	}
	return o.GrantTypes
}

// GetGrantTypesOk returns a tuple with the GrantTypes field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetExchangeAppsResponseInner) GetGrantTypesOk() ([]string, bool) {
	if o == nil || IsNil(o.GrantTypes) {
		return nil, false
	}
	return o.GrantTypes, true
}

// HasGrantTypes returns a boolean if a field has been set.
func (o *GetExchangeAppsResponseInner) HasGrantTypes() bool {
	if o != nil && !IsNil(o.GrantTypes) {
		return true
	}

	return false
}

// SetGrantTypes gets a reference to the given []string and assigns it to the GrantTypes field.
func (o *GetExchangeAppsResponseInner) SetGrantTypes(v []string) {
	o.GrantTypes = v
}

// GetRedirectUri returns the RedirectUri field value if set, zero value otherwise.
func (o *GetExchangeAppsResponseInner) GetRedirectUri() []string {
	if o == nil || IsNil(o.RedirectUri) {
		var ret []string
		return ret
	}
	return o.RedirectUri
}

// GetRedirectUriOk returns a tuple with the RedirectUri field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetExchangeAppsResponseInner) GetRedirectUriOk() ([]string, bool) {
	if o == nil || IsNil(o.RedirectUri) {
		return nil, false
	}
	return o.RedirectUri, true
}

// HasRedirectUri returns a boolean if a field has been set.
func (o *GetExchangeAppsResponseInner) HasRedirectUri() bool {
	if o != nil && !IsNil(o.RedirectUri) {
		return true
	}

	return false
}

// SetRedirectUri gets a reference to the given []string and assigns it to the RedirectUri field.
func (o *GetExchangeAppsResponseInner) SetRedirectUri(v []string) {
	o.RedirectUri = v
}

func (o GetExchangeAppsResponseInner) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GetExchangeAppsResponseInner) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Name) {
		toSerialize["name"] = o.Name
	}
	if !IsNil(o.Description) {
		toSerialize["description"] = o.Description
	}
	if o.Url.IsSet() {
		toSerialize["url"] = o.Url.Get()
	}
	if !IsNil(o.MasterOrganizationId) {
		toSerialize["masterOrganizationId"] = o.MasterOrganizationId
	}
	if !IsNil(o.Id) {
		toSerialize["id"] = o.Id
	}
	if !IsNil(o.ClientId) {
		toSerialize["clientId"] = o.ClientId
	}
	if !IsNil(o.ClientSecret) {
		toSerialize["clientSecret"] = o.ClientSecret
	}
	if !IsNil(o.ClientProvider) {
		toSerialize["clientProvider"] = o.ClientProvider
	}
	if !IsNil(o.GrantTypes) {
		toSerialize["grantTypes"] = o.GrantTypes
	}
	if !IsNil(o.RedirectUri) {
		toSerialize["redirectUri"] = o.RedirectUri
	}
	return toSerialize, nil
}

type NullableGetExchangeAppsResponseInner struct {
	value *GetExchangeAppsResponseInner
	isSet bool
}

func (v NullableGetExchangeAppsResponseInner) Get() *GetExchangeAppsResponseInner {
	return v.value
}

func (v *NullableGetExchangeAppsResponseInner) Set(val *GetExchangeAppsResponseInner) {
	v.value = val
	v.isSet = true
}

func (v NullableGetExchangeAppsResponseInner) IsSet() bool {
	return v.isSet
}

func (v *NullableGetExchangeAppsResponseInner) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetExchangeAppsResponseInner(val *GetExchangeAppsResponseInner) *NullableGetExchangeAppsResponseInner {
	return &NullableGetExchangeAppsResponseInner{value: val, isSet: true}
}

func (v NullableGetExchangeAppsResponseInner) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetExchangeAppsResponseInner) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


