/*
Exchange Apps

Description of the Exchange Apps API

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package exchange_apps

import (
	"encoding/json"
)

// checks if the DeleteExchangeClientApp404Response type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &DeleteExchangeClientApp404Response{}

// DeleteExchangeClientApp404Response struct for DeleteExchangeClientApp404Response
type DeleteExchangeClientApp404Response struct {
	Status *int32 `json:"status,omitempty"`
	Message *string `json:"message,omitempty"`
}

// NewDeleteExchangeClientApp404Response instantiates a new DeleteExchangeClientApp404Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewDeleteExchangeClientApp404Response() *DeleteExchangeClientApp404Response {
	this := DeleteExchangeClientApp404Response{}
	return &this
}

// NewDeleteExchangeClientApp404ResponseWithDefaults instantiates a new DeleteExchangeClientApp404Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewDeleteExchangeClientApp404ResponseWithDefaults() *DeleteExchangeClientApp404Response {
	this := DeleteExchangeClientApp404Response{}
	return &this
}

// GetStatus returns the Status field value if set, zero value otherwise.
func (o *DeleteExchangeClientApp404Response) GetStatus() int32 {
	if o == nil || IsNil(o.Status) {
		var ret int32
		return ret
	}
	return *o.Status
}

// GetStatusOk returns a tuple with the Status field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DeleteExchangeClientApp404Response) GetStatusOk() (*int32, bool) {
	if o == nil || IsNil(o.Status) {
		return nil, false
	}
	return o.Status, true
}

// HasStatus returns a boolean if a field has been set.
func (o *DeleteExchangeClientApp404Response) HasStatus() bool {
	if o != nil && !IsNil(o.Status) {
		return true
	}

	return false
}

// SetStatus gets a reference to the given int32 and assigns it to the Status field.
func (o *DeleteExchangeClientApp404Response) SetStatus(v int32) {
	o.Status = &v
}

// GetMessage returns the Message field value if set, zero value otherwise.
func (o *DeleteExchangeClientApp404Response) GetMessage() string {
	if o == nil || IsNil(o.Message) {
		var ret string
		return ret
	}
	return *o.Message
}

// GetMessageOk returns a tuple with the Message field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DeleteExchangeClientApp404Response) GetMessageOk() (*string, bool) {
	if o == nil || IsNil(o.Message) {
		return nil, false
	}
	return o.Message, true
}

// HasMessage returns a boolean if a field has been set.
func (o *DeleteExchangeClientApp404Response) HasMessage() bool {
	if o != nil && !IsNil(o.Message) {
		return true
	}

	return false
}

// SetMessage gets a reference to the given string and assigns it to the Message field.
func (o *DeleteExchangeClientApp404Response) SetMessage(v string) {
	o.Message = &v
}

func (o DeleteExchangeClientApp404Response) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o DeleteExchangeClientApp404Response) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Status) {
		toSerialize["status"] = o.Status
	}
	if !IsNil(o.Message) {
		toSerialize["message"] = o.Message
	}
	return toSerialize, nil
}

type NullableDeleteExchangeClientApp404Response struct {
	value *DeleteExchangeClientApp404Response
	isSet bool
}

func (v NullableDeleteExchangeClientApp404Response) Get() *DeleteExchangeClientApp404Response {
	return v.value
}

func (v *NullableDeleteExchangeClientApp404Response) Set(val *DeleteExchangeClientApp404Response) {
	v.value = val
	v.isSet = true
}

func (v NullableDeleteExchangeClientApp404Response) IsSet() bool {
	return v.isSet
}

func (v *NullableDeleteExchangeClientApp404Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableDeleteExchangeClientApp404Response(val *DeleteExchangeClientApp404Response) *NullableDeleteExchangeClientApp404Response {
	return &NullableDeleteExchangeClientApp404Response{value: val, isSet: true}
}

func (v NullableDeleteExchangeClientApp404Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDeleteExchangeClientApp404Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


