/*
Exchange Apps

Description of the Exchange Apps API

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package exchange_apps

import (
	"encoding/json"
)

// checks if the PostExchangeAppsReponseClientProvider type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &PostExchangeAppsReponseClientProvider{}

// PostExchangeAppsReponseClientProvider struct for PostExchangeAppsReponseClientProvider
type PostExchangeAppsReponseClientProvider struct {
	ProviderId NullableString `json:"providerId,omitempty"`
}

// NewPostExchangeAppsReponseClientProvider instantiates a new PostExchangeAppsReponseClientProvider object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPostExchangeAppsReponseClientProvider() *PostExchangeAppsReponseClientProvider {
	this := PostExchangeAppsReponseClientProvider{}
	return &this
}

// NewPostExchangeAppsReponseClientProviderWithDefaults instantiates a new PostExchangeAppsReponseClientProvider object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPostExchangeAppsReponseClientProviderWithDefaults() *PostExchangeAppsReponseClientProvider {
	this := PostExchangeAppsReponseClientProvider{}
	return &this
}

// GetProviderId returns the ProviderId field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *PostExchangeAppsReponseClientProvider) GetProviderId() string {
	if o == nil || IsNil(o.ProviderId.Get()) {
		var ret string
		return ret
	}
	return *o.ProviderId.Get()
}

// GetProviderIdOk returns a tuple with the ProviderId field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *PostExchangeAppsReponseClientProvider) GetProviderIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.ProviderId.Get(), o.ProviderId.IsSet()
}

// HasProviderId returns a boolean if a field has been set.
func (o *PostExchangeAppsReponseClientProvider) HasProviderId() bool {
	if o != nil && o.ProviderId.IsSet() {
		return true
	}

	return false
}

// SetProviderId gets a reference to the given NullableString and assigns it to the ProviderId field.
func (o *PostExchangeAppsReponseClientProvider) SetProviderId(v string) {
	o.ProviderId.Set(&v)
}
// SetProviderIdNil sets the value for ProviderId to be an explicit nil
func (o *PostExchangeAppsReponseClientProvider) SetProviderIdNil() {
	o.ProviderId.Set(nil)
}

// UnsetProviderId ensures that no value is present for ProviderId, not even an explicit nil
func (o *PostExchangeAppsReponseClientProvider) UnsetProviderId() {
	o.ProviderId.Unset()
}

func (o PostExchangeAppsReponseClientProvider) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o PostExchangeAppsReponseClientProvider) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if o.ProviderId.IsSet() {
		toSerialize["providerId"] = o.ProviderId.Get()
	}
	return toSerialize, nil
}

type NullablePostExchangeAppsReponseClientProvider struct {
	value *PostExchangeAppsReponseClientProvider
	isSet bool
}

func (v NullablePostExchangeAppsReponseClientProvider) Get() *PostExchangeAppsReponseClientProvider {
	return v.value
}

func (v *NullablePostExchangeAppsReponseClientProvider) Set(val *PostExchangeAppsReponseClientProvider) {
	v.value = val
	v.isSet = true
}

func (v NullablePostExchangeAppsReponseClientProvider) IsSet() bool {
	return v.isSet
}

func (v *NullablePostExchangeAppsReponseClientProvider) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePostExchangeAppsReponseClientProvider(val *PostExchangeAppsReponseClientProvider) *NullablePostExchangeAppsReponseClientProvider {
	return &NullablePostExchangeAppsReponseClientProvider{value: val, isSet: true}
}

func (v NullablePostExchangeAppsReponseClientProvider) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePostExchangeAppsReponseClientProvider) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


