/*
Exchange Apps

Description of the Exchange Apps API

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package exchange_apps

import (
	"encoding/json"
)

// checks if the GetExchangeAppContractsResponseInnerRequestedTier type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GetExchangeAppContractsResponseInnerRequestedTier{}

// GetExchangeAppContractsResponseInnerRequestedTier struct for GetExchangeAppContractsResponseInnerRequestedTier
type GetExchangeAppContractsResponseInnerRequestedTier struct {
	Id *int32 `json:"id,omitempty"`
	Name *string `json:"name,omitempty"`
	Description *string `json:"description,omitempty"`
	Limits []GetExchangeAppContractsResponseInnerRequestedTierLimitsInner `json:"limits,omitempty"`
}

// NewGetExchangeAppContractsResponseInnerRequestedTier instantiates a new GetExchangeAppContractsResponseInnerRequestedTier object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetExchangeAppContractsResponseInnerRequestedTier() *GetExchangeAppContractsResponseInnerRequestedTier {
	this := GetExchangeAppContractsResponseInnerRequestedTier{}
	return &this
}

// NewGetExchangeAppContractsResponseInnerRequestedTierWithDefaults instantiates a new GetExchangeAppContractsResponseInnerRequestedTier object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetExchangeAppContractsResponseInnerRequestedTierWithDefaults() *GetExchangeAppContractsResponseInnerRequestedTier {
	this := GetExchangeAppContractsResponseInnerRequestedTier{}
	return &this
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *GetExchangeAppContractsResponseInnerRequestedTier) GetId() int32 {
	if o == nil || IsNil(o.Id) {
		var ret int32
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetExchangeAppContractsResponseInnerRequestedTier) GetIdOk() (*int32, bool) {
	if o == nil || IsNil(o.Id) {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *GetExchangeAppContractsResponseInnerRequestedTier) HasId() bool {
	if o != nil && !IsNil(o.Id) {
		return true
	}

	return false
}

// SetId gets a reference to the given int32 and assigns it to the Id field.
func (o *GetExchangeAppContractsResponseInnerRequestedTier) SetId(v int32) {
	o.Id = &v
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *GetExchangeAppContractsResponseInnerRequestedTier) GetName() string {
	if o == nil || IsNil(o.Name) {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetExchangeAppContractsResponseInnerRequestedTier) GetNameOk() (*string, bool) {
	if o == nil || IsNil(o.Name) {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *GetExchangeAppContractsResponseInnerRequestedTier) HasName() bool {
	if o != nil && !IsNil(o.Name) {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *GetExchangeAppContractsResponseInnerRequestedTier) SetName(v string) {
	o.Name = &v
}

// GetDescription returns the Description field value if set, zero value otherwise.
func (o *GetExchangeAppContractsResponseInnerRequestedTier) GetDescription() string {
	if o == nil || IsNil(o.Description) {
		var ret string
		return ret
	}
	return *o.Description
}

// GetDescriptionOk returns a tuple with the Description field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetExchangeAppContractsResponseInnerRequestedTier) GetDescriptionOk() (*string, bool) {
	if o == nil || IsNil(o.Description) {
		return nil, false
	}
	return o.Description, true
}

// HasDescription returns a boolean if a field has been set.
func (o *GetExchangeAppContractsResponseInnerRequestedTier) HasDescription() bool {
	if o != nil && !IsNil(o.Description) {
		return true
	}

	return false
}

// SetDescription gets a reference to the given string and assigns it to the Description field.
func (o *GetExchangeAppContractsResponseInnerRequestedTier) SetDescription(v string) {
	o.Description = &v
}

// GetLimits returns the Limits field value if set, zero value otherwise.
func (o *GetExchangeAppContractsResponseInnerRequestedTier) GetLimits() []GetExchangeAppContractsResponseInnerRequestedTierLimitsInner {
	if o == nil || IsNil(o.Limits) {
		var ret []GetExchangeAppContractsResponseInnerRequestedTierLimitsInner
		return ret
	}
	return o.Limits
}

// GetLimitsOk returns a tuple with the Limits field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetExchangeAppContractsResponseInnerRequestedTier) GetLimitsOk() ([]GetExchangeAppContractsResponseInnerRequestedTierLimitsInner, bool) {
	if o == nil || IsNil(o.Limits) {
		return nil, false
	}
	return o.Limits, true
}

// HasLimits returns a boolean if a field has been set.
func (o *GetExchangeAppContractsResponseInnerRequestedTier) HasLimits() bool {
	if o != nil && !IsNil(o.Limits) {
		return true
	}

	return false
}

// SetLimits gets a reference to the given []GetExchangeAppContractsResponseInnerRequestedTierLimitsInner and assigns it to the Limits field.
func (o *GetExchangeAppContractsResponseInnerRequestedTier) SetLimits(v []GetExchangeAppContractsResponseInnerRequestedTierLimitsInner) {
	o.Limits = v
}

func (o GetExchangeAppContractsResponseInnerRequestedTier) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GetExchangeAppContractsResponseInnerRequestedTier) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Id) {
		toSerialize["id"] = o.Id
	}
	if !IsNil(o.Name) {
		toSerialize["name"] = o.Name
	}
	if !IsNil(o.Description) {
		toSerialize["description"] = o.Description
	}
	if !IsNil(o.Limits) {
		toSerialize["limits"] = o.Limits
	}
	return toSerialize, nil
}

type NullableGetExchangeAppContractsResponseInnerRequestedTier struct {
	value *GetExchangeAppContractsResponseInnerRequestedTier
	isSet bool
}

func (v NullableGetExchangeAppContractsResponseInnerRequestedTier) Get() *GetExchangeAppContractsResponseInnerRequestedTier {
	return v.value
}

func (v *NullableGetExchangeAppContractsResponseInnerRequestedTier) Set(val *GetExchangeAppContractsResponseInnerRequestedTier) {
	v.value = val
	v.isSet = true
}

func (v NullableGetExchangeAppContractsResponseInnerRequestedTier) IsSet() bool {
	return v.isSet
}

func (v *NullableGetExchangeAppContractsResponseInnerRequestedTier) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetExchangeAppContractsResponseInnerRequestedTier(val *GetExchangeAppContractsResponseInnerRequestedTier) *NullableGetExchangeAppContractsResponseInnerRequestedTier {
	return &NullableGetExchangeAppContractsResponseInnerRequestedTier{value: val, isSet: true}
}

func (v NullableGetExchangeAppContractsResponseInnerRequestedTier) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetExchangeAppContractsResponseInnerRequestedTier) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


