/*
Organization API

Description of the Organization API

API version: 1.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package org

import (
	"encoding/json"
)

// checks if the MonitoringCenterEntitlement type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &MonitoringCenterEntitlement{}

// MonitoringCenterEntitlement Monitoring Center entitlements
type MonitoringCenterEntitlement struct {
	// Product SKU
	ProductSKU *int32 `json:"productSKU,omitempty"`
}

// NewMonitoringCenterEntitlement instantiates a new MonitoringCenterEntitlement object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewMonitoringCenterEntitlement() *MonitoringCenterEntitlement {
	this := MonitoringCenterEntitlement{}
	var productSKU int32 = 0
	this.ProductSKU = &productSKU
	return &this
}

// NewMonitoringCenterEntitlementWithDefaults instantiates a new MonitoringCenterEntitlement object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewMonitoringCenterEntitlementWithDefaults() *MonitoringCenterEntitlement {
	this := MonitoringCenterEntitlement{}
	var productSKU int32 = 0
	this.ProductSKU = &productSKU
	return &this
}

// GetProductSKU returns the ProductSKU field value if set, zero value otherwise.
func (o *MonitoringCenterEntitlement) GetProductSKU() int32 {
	if o == nil || IsNil(o.ProductSKU) {
		var ret int32
		return ret
	}
	return *o.ProductSKU
}

// GetProductSKUOk returns a tuple with the ProductSKU field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MonitoringCenterEntitlement) GetProductSKUOk() (*int32, bool) {
	if o == nil || IsNil(o.ProductSKU) {
		return nil, false
	}
	return o.ProductSKU, true
}

// HasProductSKU returns a boolean if a field has been set.
func (o *MonitoringCenterEntitlement) HasProductSKU() bool {
	if o != nil && !IsNil(o.ProductSKU) {
		return true
	}

	return false
}

// SetProductSKU gets a reference to the given int32 and assigns it to the ProductSKU field.
func (o *MonitoringCenterEntitlement) SetProductSKU(v int32) {
	o.ProductSKU = &v
}

func (o MonitoringCenterEntitlement) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o MonitoringCenterEntitlement) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.ProductSKU) {
		toSerialize["productSKU"] = o.ProductSKU
	}
	return toSerialize, nil
}

type NullableMonitoringCenterEntitlement struct {
	value *MonitoringCenterEntitlement
	isSet bool
}

func (v NullableMonitoringCenterEntitlement) Get() *MonitoringCenterEntitlement {
	return v.value
}

func (v *NullableMonitoringCenterEntitlement) Set(val *MonitoringCenterEntitlement) {
	v.value = val
	v.isSet = true
}

func (v NullableMonitoringCenterEntitlement) IsSet() bool {
	return v.isSet
}

func (v *NullableMonitoringCenterEntitlement) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableMonitoringCenterEntitlement(val *MonitoringCenterEntitlement) *NullableMonitoringCenterEntitlement {
	return &NullableMonitoringCenterEntitlement{value: val, isSet: true}
}

func (v NullableMonitoringCenterEntitlement) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableMonitoringCenterEntitlement) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


